# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!
import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *

class Ui_MainWindow(QtWidgets.QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1104, 636)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1101, 591))
        self.tabWidget.setObjectName("tabWidget")
        self.init_tab = QtWidgets.QWidget()
        self.init_tab.setObjectName("init_tab")
        self.pushButton = QtWidgets.QPushButton(self.init_tab)
        self.pushButton.setGeometry(QtCore.QRect(10, 10, 101, 23))
        self.pushButton.setCheckable(True)
        self.pushButton.setObjectName("pushButton")
        self.tabWidget.addTab(self.init_tab, "")
        self.pressure_animation = QtWidgets.QWidget()
        self.pressure_animation.setObjectName("pressure_animation")
        self.label_11 = QtWidgets.QLabel(self.pressure_animation)
        self.label_11.setGeometry(QtCore.QRect(280, 140, 111, 16))
        self.label_11.setObjectName("label_11")
        self.tabWidget.addTab(self.pressure_animation, "")
        self.saturation_animation = QtWidgets.QWidget()
        self.saturation_animation.setObjectName("saturation_animation")
        self.label_10 = QtWidgets.QLabel(self.saturation_animation)
        self.label_10.setGeometry(QtCore.QRect(290, 120, 131, 16))
        self.label_10.setObjectName("label_10")
        self.tabWidget.addTab(self.saturation_animation, "")
        self.height_map = QtWidgets.QWidget()
        self.height_map.setObjectName("height_map")
        self.label_7 = QtWidgets.QLabel(self.height_map)
        self.label_7.setGeometry(QtCore.QRect(120, 160, 151, 16))
        self.label_7.setObjectName("label_7")
        self.line = QtWidgets.QFrame(self.height_map)
        self.line.setGeometry(QtCore.QRect(1010, 50, 20, 231))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_8 = QtWidgets.QLabel(self.height_map)
        self.label_8.setGeometry(QtCore.QRect(1000, 280, 47, 13))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.height_map)
        self.label_9.setGeometry(QtCore.QRect(1000, 30, 47, 13))
        self.label_9.setObjectName("label_9")
        self.tabWidget.addTab(self.height_map, "")
        self.prod_inj_rates = QtWidgets.QWidget()
        self.prod_inj_rates.setObjectName("prod_inj_rates")
        self.label_3 = QtWidgets.QLabel(self.prod_inj_rates)
        self.label_3.setGeometry(QtCore.QRect(80, 40, 111, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.prod_inj_rates)
        self.label_4.setGeometry(QtCore.QRect(80, 190, 91, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.prod_inj_rates)
        self.label_5.setGeometry(QtCore.QRect(530, 40, 101, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.prod_inj_rates)
        self.label_6.setGeometry(QtCore.QRect(530, 200, 101, 21))
        self.label_6.setObjectName("label_6")
        self.tabWidget.addTab(self.prod_inj_rates, "")
        self.pvt_features = QtWidgets.QWidget()
        self.pvt_features.setObjectName("pvt_features")
        self.label = QtWidgets.QLabel(self.pvt_features)
        self.label.setGeometry(QtCore.QRect(130, 90, 131, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.pvt_features)
        self.label_2.setGeometry(QtCore.QRect(700, 100, 131, 41))
        self.label_2.setObjectName("label_2")
        self.tabWidget.addTab(self.pvt_features, "")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1104, 21))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Выбрать модель"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.init_tab), _translate("MainWindow", "Инициализация"))
        self.label_11.setText(_translate("MainWindow", "Анимация давления"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.pressure_animation), _translate("MainWindow", "Давление"))
        self.label_10.setText(_translate("MainWindow", "Анимация Насыщенности"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.saturation_animation), _translate("MainWindow", "Насыщенность"))
        self.label_7.setText(_translate("MainWindow", "Карта высот (3D или 2D)"))
        self.label_8.setText(_translate("MainWindow", "MIN"))
        self.label_9.setText(_translate("MainWindow", "MAX"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.height_map), _translate("MainWindow", "Карта высот"))
        self.label_3.setText(_translate("MainWindow", "ГРАФИК INJ_1"))
        self.label_4.setText(_translate("MainWindow", "ГРАФИК INJ_2"))
        self.label_5.setText(_translate("MainWindow", "ГРАФИК PROD_1"))
        self.label_6.setText(_translate("MainWindow", "ГРАФИК PROD_2"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.prod_inj_rates), _translate("MainWindow", "Дебит/Прием"))
        self.label.setText(_translate("MainWindow", "ГРАФИК PVT"))
        self.label_2.setText(_translate("MainWindow", "ГРАФИК КАПИЛЛЯРКИ"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.pvt_features), _translate("MainWindow", "PVT свойства"))

if __name__ == '__main__':
    
    app = QApplication(sys.argv)
    this_widget = QMainWindow()
    this_ui = Ui_MainWindow()
    this_ui.setupUi(this_widget)
    this_widget.show()
    sys.exit(app.exec_())