# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1104, 636)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1101, 591))
        self.tabWidget.setObjectName("tabWidget")
        self.init_tab = QtWidgets.QWidget()
        self.init_tab.setObjectName("init_tab")
        self.push_Button = QtWidgets.QPushButton(self.init_tab)
        self.push_Button.setGeometry(QtCore.QRect(10, 10, 101, 23))
        self.push_Button.setCheckable(True)
        self.push_Button.setObjectName("push_Button")
        self.label_12 = QtWidgets.QLabel(self.init_tab)
        self.label_12.setGeometry(QtCore.QRect(20, 60, 111, 21))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.init_tab)
        self.label_13.setGeometry(QtCore.QRect(20, 90, 91, 16))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.init_tab)
        self.label_14.setGeometry(QtCore.QRect(20, 120, 47, 13))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.init_tab)
        self.label_15.setGeometry(QtCore.QRect(20, 150, 61, 16))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.init_tab)
        self.label_16.setGeometry(QtCore.QRect(20, 180, 51, 16))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.init_tab)
        self.label_17.setGeometry(QtCore.QRect(20, 210, 71, 16))
        self.label_17.setObjectName("label_17")
        self.init_well_Button = QtWidgets.QPushButton(self.init_tab)
        self.init_well_Button.setGeometry(QtCore.QRect(140, 60, 261, 23))
        self.init_well_Button.setObjectName("init_well_Button")
        self.SCAL_Button = QtWidgets.QPushButton(self.init_tab)
        self.SCAL_Button.setGeometry(QtCore.QRect(140, 90, 261, 23))
        self.SCAL_Button.setObjectName("SCAL_Button")
        self.PVT_Button = QtWidgets.QPushButton(self.init_tab)
        self.PVT_Button.setGeometry(QtCore.QRect(140, 120, 261, 23))
        self.PVT_Button.setObjectName("PVT_Button")
        self.GRID_Button = QtWidgets.QPushButton(self.init_tab)
        self.GRID_Button.setGeometry(QtCore.QRect(140, 150, 261, 23))
        self.GRID_Button.setObjectName("GRID_Button")
        self.INIT_Button = QtWidgets.QPushButton(self.init_tab)
        self.INIT_Button.setGeometry(QtCore.QRect(140, 180, 261, 23))
        self.INIT_Button.setObjectName("INIT_Button")
        self.GPRO_Button = QtWidgets.QPushButton(self.init_tab)
        self.GPRO_Button.setGeometry(QtCore.QRect(140, 210, 261, 23))
        self.GPRO_Button.setObjectName("GPRO_Button")
        self.tabWidget.addTab(self.init_tab, "")
        self.pressure_animation = QtWidgets.QWidget()
        self.pressure_animation.setObjectName("pressure_animation")
        self.label_11 = QtWidgets.QLabel(self.pressure_animation)
        self.label_11.setGeometry(QtCore.QRect(280, 140, 111, 16))
        self.label_11.setObjectName("label_11")
        self.tabWidget.addTab(self.pressure_animation, "")
        self.saturation_animation = QtWidgets.QWidget()
        self.saturation_animation.setObjectName("saturation_animation")
        self.label_10 = QtWidgets.QLabel(self.saturation_animation)
        self.label_10.setGeometry(QtCore.QRect(290, 120, 131, 16))
        self.label_10.setObjectName("label_10")
        self.tabWidget.addTab(self.saturation_animation, "")
        self.height_map = QtWidgets.QWidget()
        self.height_map.setObjectName("height_map")
        self.label_7 = QtWidgets.QLabel(self.height_map)
        self.label_7.setGeometry(QtCore.QRect(120, 160, 151, 16))
        self.label_7.setObjectName("label_7")
        self.line = QtWidgets.QFrame(self.height_map)
        self.line.setGeometry(QtCore.QRect(1010, 50, 20, 231))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_8 = QtWidgets.QLabel(self.height_map)
        self.label_8.setGeometry(QtCore.QRect(1000, 280, 47, 13))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.height_map)
        self.label_9.setGeometry(QtCore.QRect(1000, 30, 47, 13))
        self.label_9.setObjectName("label_9")
        self.tabWidget.addTab(self.height_map, "")
        self.prod_inj_rates = QtWidgets.QWidget()
        self.prod_inj_rates.setObjectName("prod_inj_rates")
        self.label_3 = QtWidgets.QLabel(self.prod_inj_rates)
        self.label_3.setGeometry(QtCore.QRect(80, 40, 111, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.prod_inj_rates)
        self.label_4.setGeometry(QtCore.QRect(80, 190, 91, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.prod_inj_rates)
        self.label_5.setGeometry(QtCore.QRect(530, 40, 101, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.prod_inj_rates)
        self.label_6.setGeometry(QtCore.QRect(530, 200, 101, 21))
        self.label_6.setObjectName("label_6")
        self.tabWidget.addTab(self.prod_inj_rates, "")
        self.pvt_features = QtWidgets.QWidget()
        self.pvt_features.setObjectName("pvt_features")
        self.label = QtWidgets.QLabel(self.pvt_features)
        self.label.setGeometry(QtCore.QRect(130, 90, 131, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.pvt_features)
        self.label_2.setGeometry(QtCore.QRect(700, 100, 131, 41))
        self.label_2.setObjectName("label_2")
        self.tabWidget.addTab(self.pvt_features, "")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1104, 21))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.push_Button.setText(_translate("MainWindow", "Начать расчет"))
        self.label_12.setText(_translate("MainWindow", "Файл скважин(init)"))
        self.label_13.setText(_translate("MainWindow", "Файл SCAL"))
        self.label_14.setText(_translate("MainWindow", "Файл PVT"))
        self.label_15.setText(_translate("MainWindow", "Файл GRID"))
        self.label_16.setText(_translate("MainWindow", "Файл INIT"))
        self.label_17.setText(_translate("MainWindow", "Файл GPRO"))
        self.init_well_Button.setText(_translate("MainWindow", "Выбрать файл"))
        self.SCAL_Button.setText(_translate("MainWindow", "Выбрать файл"))
        self.PVT_Button.setText(_translate("MainWindow", "Выбрать файл"))
        self.GRID_Button.setText(_translate("MainWindow", "Выбрать файл"))
        self.INIT_Button.setText(_translate("MainWindow", "Выбрать файл"))
        self.GPRO_Button.setText(_translate("MainWindow", "Выбрать файл"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.init_tab), _translate("MainWindow", "Инициализация"))
        self.label_11.setText(_translate("MainWindow", "Анимация давления"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.pressure_animation), _translate("MainWindow", "Давление"))
        self.label_10.setText(_translate("MainWindow", "Анимация Насыщенности"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.saturation_animation), _translate("MainWindow", "Насыщенность"))
        self.label_7.setText(_translate("MainWindow", "Карта высот (3D или 2D)"))
        self.label_8.setText(_translate("MainWindow", "MIN"))
        self.label_9.setText(_translate("MainWindow", "MAX"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.height_map), _translate("MainWindow", "Карта высот"))
        self.label_3.setText(_translate("MainWindow", "ГРАФИК INJ_1"))
        self.label_4.setText(_translate("MainWindow", "ГРАФИК INJ_2"))
        self.label_5.setText(_translate("MainWindow", "ГРАФИК PROD_1"))
        self.label_6.setText(_translate("MainWindow", "ГРАФИК PROD_2"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.prod_inj_rates), _translate("MainWindow", "Дебит/Прием"))
        self.label.setText(_translate("MainWindow", "ГРАФИК PVT"))
        self.label_2.setText(_translate("MainWindow", "ГРАФИК КАПИЛЛЯРКИ"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.pvt_features), _translate("MainWindow", "PVT свойства"))


