# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(612, 474)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.init_tab = QtWidgets.QWidget()
        self.init_tab.setObjectName("init_tab")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.init_tab)
        self.gridLayout_8.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_8.setSpacing(6)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_7.setSpacing(6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.SCAL_Button = QtWidgets.QPushButton(self.init_tab)
        self.SCAL_Button.setObjectName("SCAL_Button")
        self.gridLayout_7.addWidget(self.SCAL_Button, 2, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.init_tab)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_7.addWidget(self.label_13, 2, 0, 1, 1)
        self.init_well_Button = QtWidgets.QPushButton(self.init_tab)
        self.init_well_Button.setObjectName("init_well_Button")
        self.gridLayout_7.addWidget(self.init_well_Button, 1, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.init_tab)
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_7.addWidget(self.label_17, 6, 0, 1, 1)
        self.GPRO_Button = QtWidgets.QPushButton(self.init_tab)
        self.GPRO_Button.setObjectName("GPRO_Button")
        self.gridLayout_7.addWidget(self.GPRO_Button, 6, 1, 1, 1)
        self.PVT_Button = QtWidgets.QPushButton(self.init_tab)
        self.PVT_Button.setObjectName("PVT_Button")
        self.gridLayout_7.addWidget(self.PVT_Button, 3, 1, 1, 1)
        self.push_Button = QtWidgets.QPushButton(self.init_tab)
        self.push_Button.setCheckable(True)
        self.push_Button.setObjectName("push_Button")
        self.gridLayout_7.addWidget(self.push_Button, 0, 1, 1, 1)
        self.GRID_Button = QtWidgets.QPushButton(self.init_tab)
        self.GRID_Button.setObjectName("GRID_Button")
        self.gridLayout_7.addWidget(self.GRID_Button, 4, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.init_tab)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_7.addWidget(self.label_12, 1, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.init_tab)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_7.addWidget(self.label_15, 4, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.init_tab)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_7.addWidget(self.label_14, 3, 0, 1, 1)
        self.INIT_Button = QtWidgets.QPushButton(self.init_tab)
        self.INIT_Button.setObjectName("INIT_Button")
        self.gridLayout_7.addWidget(self.INIT_Button, 5, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.init_tab)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_7.addWidget(self.label_16, 5, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem, 1, 2, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem1, 1, 0, 1, 1)
        self.tabWidget.addTab(self.init_tab, "")
        self.pressure_animation = QtWidgets.QWidget()
        self.pressure_animation.setObjectName("pressure_animation")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.pressure_animation)
        self.gridLayout_5.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_5.setSpacing(6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.pressure_animation)
        self.pushButton.setMaximumSize(QtCore.QSize(25, 16777215))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.pressure_animation)
        self.pushButton_2.setMaximumSize(QtCore.QSize(25, 16777215))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.pressure_animation)
        self.pushButton_3.setMaximumSize(QtCore.QSize(25, 16777215))
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.pressure_animation)
        self.pushButton_4.setMaximumSize(QtCore.QSize(25, 16777215))
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.horizontalSlider = QtWidgets.QSlider(self.pressure_animation)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalLayout.addWidget(self.horizontalSlider)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.widget = QtWidgets.QWidget(self.pressure_animation)
        self.widget.setMinimumSize(QtCore.QSize(0, 325))
        self.widget.setObjectName("widget")
        self.verticalLayout.addWidget(self.widget)
        self.gridLayout_5.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.pressure_animation, "")
        self.saturation_animation = QtWidgets.QWidget()
        self.saturation_animation.setObjectName("saturation_animation")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.saturation_animation)
        self.gridLayout_4.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_5 = QtWidgets.QPushButton(self.saturation_animation)
        self.pushButton_5.setMaximumSize(QtCore.QSize(25, 16777215))
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_2.addWidget(self.pushButton_5)
        self.pushButton_6 = QtWidgets.QPushButton(self.saturation_animation)
        self.pushButton_6.setMaximumSize(QtCore.QSize(25, 16777215))
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_2.addWidget(self.pushButton_6)
        self.pushButton_7 = QtWidgets.QPushButton(self.saturation_animation)
        self.pushButton_7.setMaximumSize(QtCore.QSize(25, 16777215))
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_2.addWidget(self.pushButton_7)
        self.pushButton_8 = QtWidgets.QPushButton(self.saturation_animation)
        self.pushButton_8.setMaximumSize(QtCore.QSize(25, 16777215))
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_2.addWidget(self.pushButton_8)
        self.horizontalSlider_2 = QtWidgets.QSlider(self.saturation_animation)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.horizontalLayout_2.addWidget(self.horizontalSlider_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.widget_2 = QtWidgets.QWidget(self.saturation_animation)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 325))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2.addWidget(self.widget_2)
        self.gridLayout_4.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.saturation_animation, "")
        self.height_map = QtWidgets.QWidget()
        self.height_map.setObjectName("height_map")
        self.label_7 = QtWidgets.QLabel(self.height_map)
        self.label_7.setGeometry(QtCore.QRect(120, 160, 151, 16))
        self.label_7.setObjectName("label_7")
        self.line = QtWidgets.QFrame(self.height_map)
        self.line.setGeometry(QtCore.QRect(1010, 50, 20, 231))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_8 = QtWidgets.QLabel(self.height_map)
        self.label_8.setGeometry(QtCore.QRect(1000, 280, 47, 13))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.height_map)
        self.label_9.setGeometry(QtCore.QRect(1000, 30, 47, 13))
        self.label_9.setObjectName("label_9")
        self.tabWidget.addTab(self.height_map, "")
        self.prod_inj_rates = QtWidgets.QWidget()
        self.prod_inj_rates.setObjectName("prod_inj_rates")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.prod_inj_rates)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.prod_inj_rates)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.prod_inj_rates)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.prod_inj_rates)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.prod_inj_rates)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.prod_inj_rates, "")
        self.pvt_features = QtWidgets.QWidget()
        self.pvt_features.setObjectName("pvt_features")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.pvt_features)
        self.gridLayout_6.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_6.setSpacing(6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.pvt_features)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(self.pvt_features)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.gridLayout_6.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.tabWidget.addTab(self.pvt_features, "")
        self.gridLayout_3.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 612, 21))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.SCAL_Button.setText(_translate("MainWindow", "Выбрать файл"))
        self.label_13.setText(_translate("MainWindow", "Файл SCAL"))
        self.init_well_Button.setText(_translate("MainWindow", "Выбрать файл"))
        self.label_17.setText(_translate("MainWindow", "Файл GPRO"))
        self.GPRO_Button.setText(_translate("MainWindow", "Выбрать файл"))
        self.PVT_Button.setText(_translate("MainWindow", "Выбрать файл"))
        self.push_Button.setText(_translate("MainWindow", "Начать расчет"))
        self.GRID_Button.setText(_translate("MainWindow", "Выбрать файл"))
        self.label_12.setText(_translate("MainWindow", "Файл скважин(init)"))
        self.label_15.setText(_translate("MainWindow", "Файл GRID"))
        self.label_14.setText(_translate("MainWindow", "Файл PVT"))
        self.INIT_Button.setText(_translate("MainWindow", "Выбрать файл"))
        self.label_16.setText(_translate("MainWindow", "Файл INIT"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.init_tab), _translate("MainWindow", "Инициализация"))
        self.pushButton.setText(_translate("MainWindow", "<<"))
        self.pushButton_2.setText(_translate("MainWindow", "||"))
        self.pushButton_3.setText(_translate("MainWindow", ">"))
        self.pushButton_4.setText(_translate("MainWindow", ">>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.pressure_animation), _translate("MainWindow", "Давление"))
        self.pushButton_5.setText(_translate("MainWindow", "<<"))
        self.pushButton_6.setText(_translate("MainWindow", "||"))
        self.pushButton_7.setText(_translate("MainWindow", ">"))
        self.pushButton_8.setText(_translate("MainWindow", ">>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.saturation_animation), _translate("MainWindow", "Насыщенность"))
        self.label_7.setText(_translate("MainWindow", "Карта высот (3D или 2D)"))
        self.label_8.setText(_translate("MainWindow", "MIN"))
        self.label_9.setText(_translate("MainWindow", "MAX"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.height_map), _translate("MainWindow", "Карта высот"))
        self.label_3.setText(_translate("MainWindow", "ГРАФИК INJ_1"))
        self.label_4.setText(_translate("MainWindow", "ГРАФИК INJ_2"))
        self.label_6.setText(_translate("MainWindow", "ГРАФИК PROD_2"))
        self.label_5.setText(_translate("MainWindow", "ГРАФИК PROD_1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.prod_inj_rates), _translate("MainWindow", "Дебит/Прием"))
        self.label_2.setText(_translate("MainWindow", "ГРАФИК КАПИЛЛЯРКИ"))
        self.label.setText(_translate("MainWindow", "ГРАФИК PVT"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.pvt_features), _translate("MainWindow", "PVT свойства"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

