#ifndef LIB_SIMPLE_SOLVER_GLOBAL_H
#define LIB_SIMPLE_SOLVER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIB_SIMPLE_SOLVER_LIBRARY)
#  define LIB_SIMPLE_SOLVERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LIB_SIMPLE_SOLVERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LIB_SIMPLE_SOLVER_GLOBAL_H
