#ifndef LOGGER_H
#define LOGGER_H

#include <QLoggingCategory>

Q_DECLARE_LOGGING_CATEGORY(logRead)
Q_DECLARE_LOGGING_CATEGORY(logInit)
Q_DECLARE_LOGGING_CATEGORY(logSolve)
Q_DECLARE_LOGGING_CATEGORY(logHDF5)

#endif // LOGGER_H
